### ISSUE TITLE
Advice to use openrouteservice or Mapbox router

### ISSUE THREAD

**Issue by A-contresens** [perliedman/mapbox-gl-routing-machine#1]
I am migrating from leaflet to Mapbox gl and I was using Leaflet Open Routing Machine with openrouteservice.

Do you have plan to add openrouteservice or Mapbox router or do you have any advice to create an adapter ?

Thanks

**Comment by perliedman** [comment]
Hi, I am not actively working on this project, as you might have guessed. So the answer to your question is no.

I hope you find a solution and perhaps can find some use from the code in this repository. Good luck!
